// gameface-templates/svelte/src/components/CarouselMenu.svelte
<script lang="ts">
  import type { GameMode } from '../data/types';
  import styles from './CarouselMenu.module.scss';
  import CarouselCard from './CarouselCard.svelte';

  let {
    items,
    selectedId,
    onSelect,
  }: {
    items: GameMode[];
    selectedId: string;
    onSelect: (id: string) => void;
  } = $props();
</script>

<div class={styles['carousel-menu']}>
  {#each items as item (item.id)}
    <CarouselCard
      {item}
      isSelected={item.id === selectedId}
      {onSelect}
    />
  {/each}
</div>

// gameface-templates/vue/src/components/CarouselMenu.vue
<script setup lang="ts">
import type { GameMode } from '../data/types';
import styles from './CarouselMenu.module.scss';
import CarouselCard from './CarouselCard.vue';

defineProps<{
  items: GameMode[];
  selectedId: string;
}>();

const emit = defineEmits<{
  select: [id: string];
}>();
</script>

<template>
  <div :class="styles['carousel-menu']">
    <CarouselCard
      v-for="item in items"
      :key="item.id"
      :item="item"
      :is-selected="item.id === selectedId"
      @select="emit('select', $event)"
    />
  </div>
</template>
